name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    
    - name: Build the C# code
      run: dotnet build 
    
    - name: Builds the Typescript code
      working-directory: ./DotnetTemplate.Web
      run: |
        npm install
        npm run build

    - name: Run the C# tests
      working-directory: ./DotnetTemplate.Web.Tests
      run: dotnet test

    - name: Runs the typeScript tests and he TypeScript code
      working-directory: ./DotnetTemplate.Web
      run: |
        npm t
        npm run lint